pool:
  vmImage: 'ubuntu-18.04'

 
jobs:
- job: Foo
  condition: ne(variables['IntegrationTests'], 'false')
  steps:
  - script: echo Hello!

- job: Bar
  dependsOn: Foo
  condition: in(dependencies.Foo.result, 'Succeeded', 'Skipped')

  steps:
  - task: PowerShell@2
    displayName: 'Updating Clickup Board'
    inputs:
      targetType: 'Inline'
      script: |
        echo $env:PathApi
    env:
      PathApi: $[variables.PathApi]


- job: Bar2
  dependsOn: Bar
  condition: in(dependencies.Bar.result, 'Succeeded', 'Skipped')

  steps:
  - script: echo Hello from bar2!