name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

jobs:
- job: Bar

  steps:

  - script: |
      npm -version
    displayName: 'Npm version'
      
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-eleva'
      command: 'run'
      arguments: '-it -d nginx'

  - script: echo "hello world" >> hello.txt

  - publish: $(System.DefaultWorkingDirectory/*

  