name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

jobs:
- job: Bar

  steps:

  - script: |
      npm -version
    displayName: 'Npm version'
      

  - script: echo "hello world" >> hello.txt

  - publish: '*'

  