name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
    - develop
pr: none

stages:
- stage: Test
  displayName: Test
  
  jobs:
  - job: Integration
    displayName: 'Integration Tests e2e'

    steps: 
      - script: |
          sudo apt-get update
          sudo apt-get install elixir
      - script: |
          elixir -v
