name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

trigger:
  branches:
    include:
    - master
    - develop
pr: none

stages:
- stage: Test
  displayName: Test
  
  jobs:
  - job: Integration
    displayName: 'Integration Tests e2e'

    steps: 
      - script: |
          sudo -- sh -c "echo 127.0.0.1 dev.local >> /etc/hosts"
          cat /etc/hosts
          ls
          npx serve --symlinks --cors --no-clipboard --single -l tcp://dev.local:8080 dist  > /dev/null &
          curl http://localhost:8080
