pool:
  name: n

jobs:
- job: Bar

  steps:
  - task: PowerShell@2
    displayName: 'Updating Clickup Board'
    inputs:
      targetType: 'Inline'
      script: |
        ls
        cat .\azure.pipelines.yaml
